### ISSUE TITLE
The buttons back down indefinitely until hovered over again.

### ISSUE THREAD

**Issue by DillyzThe1** [impostor5875/Kolor-Kingdom#2]
<b>The Problem:</b>
* Clicking a button more than once (or a button that has no function) causes the other buttons to back up indefinitely.

<b>Problems Caused:</b>
* This will make a button that has not been watched by the player completely inaccessible. 

<b>Reproduction Of The Issue:</b>
* Open the game, and spam a button that is not fully implemented.
* Can also be caused by spamming a button that works with delay.

<b>Affected Versions:</b>
* 0.0.0.0.0.0.0.0.0.1 Pre-release

<b>Proof/Demonstration:<b>
* https://user-images.githubusercontent.com/34419642/178126105-37b7276a-278b-489e-9345-ae08b65ea2c2.mp4

**Comment by impostor5875** [comment]
alright, will fix this in version 0.0.1 (will also include a palace select screen)

**Comment by impostor5875** [comment]
fixed
