### ISSUE TITLE
The player's debug sprites lack offsetting, causing teleportation.

### ISSUE THREAD

**Issue by DillyzThe1** [impostor5875/Kolor-Kingdom#3]
<b>The Problem:</b>
* The main character's debug sprites, Uncle Fred running, has a problem with his flipped running animation.

<b>Problems Caused:</b>
*  The player starts teleporting when moving facing towards the left.

<b>Reproduction Of The Issue:</b>
* Open the game, start the gameplay, and then proceed to run around facing to the left. You will begin to teleport away from the center.

<b>Affected Versions:</b>
* 0.0.0.0.0.0.0.0.0.1 Pre-release

<b>Proof/Demonstration:<b>

**Comment by impostor5875** [comment]
i'll fix this in version 0.0.1 too

**Comment by DillyzThe1** [comment]
you can use the offsetstate code from my game if you need

**Comment by impostor5875** [comment]
:thubm_up:

**Comment by impostor5875** [comment]
fixed

**Comment by DillyzThe1** [comment]
🤓🤓🤓🤓🤓🤓
